### ISSUE TITLE
How do I specify port?

### ISSUE THREAD

**Issue by Jared-Dahlke** [tgbv/onion-tools#1]
hello,
How do I specify which local port the onion URL points to?

something like this?
```
const randomDomainObj = await generateV3OnionDomain('adfadfadfadfadfadff', 3000)
```

**Comment by tgbv** [comment]
Hello! This package does not facilitate the creation of onion servers. It's only for onion domain manipulation.

Therefore you can't specify listening ports, as those are not part of domain. Those are specified by the torrc file, or by HiddenServicePort flag
